spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sakila?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: pass

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

app:
  sql:
    slow-threshold-ms: 200
  aop:
    service-slow-threshold-ms: 300

logging:
  level:
    net.ttddyy.dsproxy.listener: INFO
    SLOW_SQL: WARN
    SERVICE_COST: INFO
